import { useEffect, useRef, useState } from 'react'
import { Archive, FileUp, FolderOpen, Pencil, Plus, RefreshCw, Trash2 } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { createDevFlow, deleteLabFlow, fetchLabFlowFiles, fetchLabFlows, importCartridgePackage, openLabFlowDirectory, saveLabFlowFile, type FlowLabItem } from '../api.ts'
import { showToast } from '../toast.tsx'
import { NextButton, NextDialog, NextEmpty, NextLoading, NextNotice, NextPage, NextPanel, NextStatus } from './NextUi.tsx'

function protocol(flow: FlowLabItem) { return flow.runtime_contract?.protocol_version ? `CF-FARP@${flow.runtime_contract.protocol_version}` : '协议待声明' }

export default function NextProjectsPage() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const picker = useRef<HTMLInputElement>(null)
  const [flows, setFlows] = useState<FlowLabItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState('')
  const [createOpen, setCreateOpen] = useState(params.get('create') === '1'); const [editFlow, setEditFlow] = useState<FlowLabItem | null>(null); const [editName, setEditName] = useState(''); const [editDescription, setEditDescription] = useState(''); const [editLoading, setEditLoading] = useState(false)

  async function load() { setLoading(true); setError(''); try { const result = await fetchLabFlows(); setFlows(result.items || []) } catch (reason: any) { setError(reason?.message || '读取卡带失败') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  useEffect(() => { if (params.get('import') === '1') picker.current?.click() }, [params])
  async function handleImport(file?: File) { if (!file) return; setBusy('import'); try { const result = await importCartridgePackage(file, 'keep_existing'); showToast({ title: '导入成功', type: 'success' }); await load(); navigate(`/projects/${encodeURIComponent(result.cartridge.id)}/design`) } catch (reason: any) { setError(reason?.message || '导入失败') } finally { setBusy('') } }
  async function handleCreate(flowId: string, name: string, description: string) { if (!flowId.trim() || !name.trim()) return; setBusy('create'); try { const result = await createDevFlow(flowId.trim(), name.trim(), description.trim()); showToast({ title: '卡带创建成功', type: 'success' }); setCreateOpen(false); await load(); navigate(`/projects/${encodeURIComponent(result.id)}/design`) } catch (reason: any) { setError(reason?.message || '创建失败') } finally { setBusy('') } }
  async function handleDelete(flow: FlowLabItem) { if (!window.confirm(`确定删除“${flow.name}”吗？此操作会删除开发卡带目录。`)) return; setBusy(`delete:${flow.id}`); try { await deleteLabFlow(flow.id); showToast({ title: '卡带已删除', type: 'success' }); await load() } catch (reason: any) { setError(reason?.message || '删除失败') } finally { setBusy('') } }
  async function openDirectory(flow: FlowLabItem) { setBusy(`open:${flow.id}`); try { await openLabFlowDirectory(flow.id) } catch (reason: any) { setError(reason?.message || '无法打开目录') } finally { setBusy('') } }
  async function openEdit(flow: FlowLabItem) { setEditFlow(flow); setEditLoading(true); try { const result = await fetchLabFlowFiles(flow.id); const manifest = result.files.manifest ? JSON.parse(result.files.manifest) : {}; setEditName(String(manifest.name || flow.name)); setEditDescription(String(manifest.description || flow.description || '')) } catch (reason: any) { setError(reason?.message || '读取卡带信息失败'); setEditFlow(null) } finally { setEditLoading(false) } }
  async function saveEdit() { if (!editFlow) return; setBusy('edit'); try { const result = await fetchLabFlowFiles(editFlow.id); const manifest = result.files.manifest ? JSON.parse(result.files.manifest) : {}; await saveLabFlowFile(editFlow.id, 'manifest', `${JSON.stringify({ ...manifest, name: editName.trim(), description: editDescription.trim() }, null, 2)}\n`); setEditFlow(null); showToast({ title: '卡带信息已保存', type: 'success' }); await load() } catch (reason: any) { setError(reason?.message || '保存失败') } finally { setBusy('') } }

  return <NextPage page="projects" title="卡带管理" description="管理可迁移的 Flow、模型配方、工具与交付卡带。" right={<><input ref={picker} type="file" accept=".zip,.cartridge.zip" hidden onChange={(event) => void handleImport(event.target.files?.[0])} /><NextButton onClick={() => picker.current?.click()} disabled={busy === 'import'}><FileUp size={15} />导入</NextButton><NextButton onClick={() => void load()} disabled={loading}><RefreshCw size={15} />刷新</NextButton><NextButton variant="primary" onClick={() => setCreateOpen(true)}><Plus size={16} />新建</NextButton></>}>
    {error && <NextNotice tone="danger" onClose={() => setError('')}>{error}</NextNotice>}
    {loading && <NextLoading label="正在读取卡带目录" />}
    {!loading && !error && !flows.length && <NextPanel className="nx-project-empty"><NextEmpty icon={<Archive size={26} />} title="从第一张卡带开始" description="把一个专属服务的流程、模型配方和交付方式整理成可运行、可迁移的卡带。" action={<div className="nx-empty-actions"><NextButton variant="primary" onClick={() => setCreateOpen(true)}>创建开发卡带</NextButton><NextButton onClick={() => picker.current?.click()}>导入已有卡带</NextButton></div>} /></NextPanel>}
    {!loading && flows.length > 0 && <div className="nx-project-stage"><div className="nx-project-group-head"><strong>开发 Flow</strong><span>{flows.length}</span></div><div className="nx-project-grid">{flows.map((flow) => <article className="nx-project-card" key={flow.id} onDoubleClick={() => navigate(`/projects/${encodeURIComponent(flow.id)}/design`)}><header><div className="nx-project-title"><span className={`nx-project-dot ${flow.editable ? 'editable' : 'readonly'}`} /><strong>{flow.name}</strong><NextStatus tone={flow.editable ? 'success' : 'neutral'}>{flow.editable ? '开发中可修改' : '只读'}</NextStatus></div><NextButton variant="link" onClick={() => navigate(`/projects/${encodeURIComponent(flow.id)}/design`)}>进入工作台 →</NextButton></header><p>{flow.description || '还没有填写卡带描述。'}</p><div className="nx-project-meta"><div><span>卡带 ID</span><code>{flow.id}</code></div><div><span>版本</span><code>v{flow.version}</code></div><div><span>协议</span><code>{protocol(flow)}</code></div><div><span>环境</span><code>{flow.runtime?.type || 'none'}</code></div><div><span>运行类型</span><code>{flow.runtime?.adapter || '开发运行'}</code></div></div><footer><NextButton onClick={() => void openEdit(flow)}><Pencil size={14} />编辑信息</NextButton><NextButton onClick={() => navigate(`/projects/${encodeURIComponent(flow.id)}/resources`)}>资源绑定</NextButton><NextButton disabled={busy === `open:${flow.id}`} onClick={() => void openDirectory(flow)}><FolderOpen size={14} />{busy === `open:${flow.id}` ? '打开中' : '打开目录'}</NextButton>{flow.editable && <NextButton variant="danger" disabled={busy === `delete:${flow.id}`} onClick={() => void handleDelete(flow)}><Trash2 size={14} />删除卡带</NextButton>}</footer></article>)}</div></div>}
    <NextDialog title="新建开发卡带" eyebrow="CREATE CARTRIDGE" open={createOpen} onClose={() => setCreateOpen(false)}><CreateForm busy={busy === 'create'} onCancel={() => setCreateOpen(false)} onSubmit={(flowId, name, description) => void handleCreate(flowId, name, description)} /></NextDialog>
    <NextDialog title={editFlow?.editable ? '编辑卡带信息' : '卡带信息'} eyebrow="CARTRIDGE PROFILE" open={Boolean(editFlow)} onClose={() => !busy && setEditFlow(null)}><div className="nx-form">{editLoading ? <NextLoading label="正在读取卡带信息" /> : <><label><span>卡带名称</span><input value={editName} onChange={(event) => setEditName(event.target.value)} disabled={!editFlow?.editable} /></label><label><span>卡带描述</span><textarea value={editDescription} onChange={(event) => setEditDescription(event.target.value)} disabled={!editFlow?.editable} rows={4} /></label><div className="nx-form-actions"><NextButton onClick={() => setEditFlow(null)}>取消</NextButton>{editFlow?.editable && <NextButton variant="primary" disabled={busy === 'edit'} onClick={() => void saveEdit()}>{busy === 'edit' ? '保存中…' : '保存修改'}</NextButton>}</div></>}</div></NextDialog>
  </NextPage>
}

function CreateForm({ busy, onCancel, onSubmit }: { busy: boolean; onCancel: () => void; onSubmit: (id: string, name: string, description: string) => void }) {
  const [id, setId] = useState('dev.'); const [name, setName] = useState(''); const [description, setDescription] = useState('')
  return <div className="nx-form"><label><span>卡带 ID</span><input value={id} onChange={(event) => setId(event.target.value)} placeholder="dev.my-flow" /></label><label><span>名称</span><input value={name} onChange={(event) => setName(event.target.value)} placeholder="例如：图片需求决策" /></label><label><span>描述</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={4} placeholder="这张卡带解决什么问题？" /></label><div className="nx-form-actions"><NextButton onClick={onCancel}>取消</NextButton><NextButton variant="primary" disabled={busy || !id.trim() || !name.trim()} onClick={() => onSubmit(id, name, description)}>{busy ? '创建中…' : '创建卡带'}</NextButton></div></div>
}
