import { useEffect, useMemo, useState } from 'react'
import { Clipboard, Download, ExternalLink, Maximize2, RefreshCw, RotateCcw, Search, Trash2 } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { controlCartridgeRun, deleteCartridgeRun, fetchCartridgeRunDiagnostics, fetchCartridgeRuns, fetchLabFlows, type FlowEvent, type RunDiagnosticBundle, type RunResult } from '../api.ts'
import { NextButton, NextDialog, NextEmpty, NextLoading, NextMetricStrip, NextNotice, NextPage, NextPanel, NextStatus, formatNextDate } from './NextUi.tsx'

type Filter = 'all' | 'attention' | 'active' | 'completed'
type Expand = '' | 'events' | 'checkpoints' | 'artifacts'
const ACTIVE = new Set(['created', 'running', 'retrying', 'recovering', 'rolling_back'])
const STATUS: Record<string, string> = { created: '已创建', running: '进行中', retrying: '重试中', recovering: '恢复中', rolling_back: '回滚中', completed: '已完成', failed: '失败', interrupted: '已中断', cancelled: '已取消', paused_waiting_user: '等待输入' }
function tone(status: string): 'success' | 'danger' | 'warning' | 'info' | 'neutral' { if (status === 'completed') return 'success'; if (['failed', 'interrupted'].includes(status)) return 'danger'; if (ACTIVE.has(status)) return 'info'; if (status === 'paused_waiting_user') return 'warning'; return 'neutral' }
function eventText(event: FlowEvent) { return event.message || event.type || event.state || '系统事件' }

export default function NextDiagnosticsPage() {
  const navigate = useNavigate(); const [params, setParams] = useSearchParams()
  const [runs, setRuns] = useState<RunResult[]>([]); const [flowNames, setFlowNames] = useState(new Map<string, string>()); const [selectedId, setSelectedId] = useState(''); const [bundle, setBundle] = useState<RunDiagnosticBundle | null>(null)
  const [filter, setFilter] = useState<Filter>(() => params.get('status') === 'attention' ? 'attention' : params.get('status') === 'completed' ? 'completed' : 'all'); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [detailLoading, setDetailLoading] = useState(false); const [busy, setBusy] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [expanded, setExpanded] = useState<Expand>('')

  async function load(selectLatest = true) { setLoading(true); setError(''); try { const [runResult, flowResult] = await Promise.all([fetchCartridgeRuns(), fetchLabFlows()]); const items = [...(runResult.items || [])].sort((a, b) => new Date(b.updated_at || b.created_at || 0).getTime() - new Date(a.updated_at || a.created_at || 0).getTime()); setRuns(items); setFlowNames(new Map((flowResult.items || []).map((flow) => [flow.id, flow.name]))); if (selectLatest && !selectedId) setSelectedId(items[0]?.run_id || '') } catch (reason: any) { setError(reason?.message || '运行记录加载失败') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  useEffect(() => { if (!selectedId) { setBundle(null); return }; let active = true; setDetailLoading(true); fetchCartridgeRunDiagnostics(selectedId).then((result) => { if (active) setBundle(result) }).catch((reason) => { if (active) setError(reason?.message || '诊断证据加载失败') }).finally(() => { if (active) setDetailLoading(false) }); return () => { active = false } }, [selectedId])
  useEffect(() => { if (!notice) return; const timer = window.setTimeout(() => setNotice(''), 2000); return () => window.clearTimeout(timer) }, [notice])

  const visible = useMemo(() => runs.filter((run) => { if (filter === 'attention' && !['failed', 'interrupted'].includes(run.status)) return false; if (filter === 'active' && !ACTIVE.has(run.status)) return false; if (filter === 'completed' && run.status !== 'completed') return false; const needle = query.trim().toLowerCase(); return !needle || [run.run_id, run.cartridge_id, flowNames.get(run.cartridge_id), run.current_state, run.error?.code, run.error?.message].some((value) => String(value || '').toLowerCase().includes(needle)) }), [filter, flowNames, query, runs])
  useEffect(() => { if (visible.length && !visible.some((run) => run.run_id === selectedId)) setSelectedId(visible[0].run_id) }, [visible, selectedId])
  const counts = useMemo(() => ({ total: runs.length, failed: runs.filter((run) => ['failed', 'interrupted'].includes(run.status)).length, active: runs.filter((run) => ACTIVE.has(run.status)).length, completed: runs.filter((run) => run.status === 'completed').length }), [runs])
  const selected = bundle?.run || runs.find((run) => run.run_id === selectedId)
  const errorEnvelope = selected?.error || selected?.errors?.at(-1)
  const artifacts = selected?.delivery?.artifacts || selected?.artifacts || []
  const checkpoints = bundle?.checkpoints || []
  const events = bundle?.events || []

  function setFilterValue(value: Filter) { setFilter(value); const next = new URLSearchParams(params); if (value === 'all') next.delete('status'); else next.set('status', value); setParams(next, { replace: true }) }
  async function recover(action: 'retry_current_node' | 'resume_checkpoint' | 'restart_run') { if (!selectedId) return; setBusy(action); setError(''); try { const next = await controlCartridgeRun(selectedId, action); setRuns((current) => current.map((run) => run.run_id === next.run_id ? next : run)); setBundle(await fetchCartridgeRunDiagnostics(next.run_id)); setNotice('恢复动作已提交') } catch (reason: any) { setError(reason?.message || '恢复失败') } finally { setBusy('') } }
  async function remove() { if (!selectedId || !window.confirm('确定删除这条运行记录吗？')) return; setBusy('delete'); try { await deleteCartridgeRun(selectedId); setSelectedId(''); setBundle(null); await load(true); setNotice('运行记录已删除') } catch (reason: any) { setError(reason?.message || '删除失败') } finally { setBusy('') } }
  function latestPayload() { return { schema: 'cartridgeflow.latest_diagnostic.v1', run: selected ? { run_id: selected.run_id, cartridge_id: selected.cartridge_id, status: selected.status, current_state: selected.current_state, error: errorEnvelope || null } : null, latest_events: events.slice(-8), latest_checkpoint: checkpoints.at(-1) || null, artifact_count: artifacts.length } }
  async function copy() { try { await navigator.clipboard.writeText(JSON.stringify(latestPayload(), null, 2)); setNotice('最近一次诊断已复制') } catch { setError('复制诊断失败') } }
  function download() { const blob = new Blob([JSON.stringify(latestPayload(), null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${selectedId || 'run'}-diagnostic.json`; anchor.click(); URL.revokeObjectURL(url) }

  const headerMetrics = <NextMetricStrip metrics={[{ label: '全部运行', value: counts.total }, { label: '失败', value: counts.failed, tone: counts.failed ? 'danger' : 'default' }, { label: '进行中', value: counts.active, tone: counts.active ? 'info' : 'default' }, { label: '已完成', value: counts.completed, tone: 'success' }]} />
  return <NextPage page="diagnostics" title="运行诊断" description="集中查看所有 Flow 的运行证据、失败原因和可安全执行的恢复动作。" right={<>{headerMetrics}<NextButton onClick={() => void load(false)}><RefreshCw size={15} />刷新记录</NextButton></>}>
    <div className="nx-diagnostics-stack">{error && <NextNotice tone="danger" onClose={() => setError('')}>{error}</NextNotice>}{notice && <NextNotice tone="success" onClose={() => setNotice('')}>{notice}</NextNotice>}<div className="nx-diagnostics-grid">
      <NextPanel className="nx-run-ledger" title="运行记录" kicker="RUN LEDGER" action={<b>{visible.length}</b>}><label className="nx-run-search"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="run_id / Flow / 错误码" /></label><div className="nx-run-filters">{([['all','全部'],['attention','异常'],['active','进行中'],['completed','已完成']] as [Filter,string][]).map(([value, label]) => <button type="button" key={value} className={filter === value ? 'active' : ''} onClick={() => setFilterValue(value)}>{label}</button>)}</div><div className="nx-run-list">{loading ? <NextLoading /> : visible.length ? visible.map((run) => <button type="button" key={run.run_id} className={selectedId === run.run_id ? 'selected' : ''} onClick={() => setSelectedId(run.run_id)}><NextStatus tone={tone(run.status)}>{STATUS[run.status] || run.status}</NextStatus><span><strong>{flowNames.get(run.cartridge_id) || run.cartridge_id}</strong><small>{run.run_id} · {run.current_state || '未知节点'}</small></span><time>{formatNextDate(run.updated_at || run.created_at)}</time></button>) : <NextEmpty title="没有符合条件的运行" />}</div></NextPanel>

      <section className="nx-selected-run">{!selected ? <NextPanel className="nx-no-run"><NextEmpty title="选择一条运行记录" description="错误证据、事件、检查点与恢复入口会显示在这里。" /></NextPanel> : <><NextPanel className="nx-selected-summary"><div className="nx-selected-head"><NextStatus tone={tone(selected.status)}>{STATUS[selected.status] || selected.status}</NextStatus><div><strong>{flowNames.get(selected.cartridge_id) || selected.cartridge_id}</strong><code>{selected.run_id}</code></div><div className="nx-selected-actions"><NextButton onClick={() => navigate(`/projects/${encodeURIComponent(selected.cartridge_id)}/test`)}><ExternalLink size={14} />打开测试台</NextButton><NextButton onClick={() => void copy()}><Clipboard size={14} />复制最近诊断</NextButton><NextButton onClick={download}><Download size={14} />导出 JSON</NextButton><NextButton variant="danger" onClick={() => void remove()} disabled={busy === 'delete' || ACTIVE.has(selected.status)}><Trash2 size={14} />删除记录</NextButton></div></div><div className="nx-cause-recovery"><section><header><span>ROOT CAUSE</span><h3>{errorEnvelope ? '发现结构化错误' : '没有失败错误'}</h3>{errorEnvelope?.code && <b>{errorEnvelope.code}</b>}</header>{errorEnvelope ? <><p>{errorEnvelope.message}</p><dl><div><dt>分类</dt><dd>{errorEnvelope.category || '未知'}</dd></div><div><dt>节点</dt><dd>{errorEnvelope.node_id || selected.current_state}</dd></div><div><dt>可重试</dt><dd>{errorEnvelope.retryable ? '是' : '否'}</dd></div></dl></> : <p>当前运行没有错误信封，可从事件与检查点确认执行路径。</p>}</section><section><header><span>RECOVERY</span><h3>恢复动作</h3><b>{errorEnvelope?.recoverable ? '允许' : '按策略'}</b></header><p>底座依据节点副作用与检查点决定哪些动作可安全执行。</p><div><NextButton disabled={Boolean(busy) || !errorEnvelope?.retryable} onClick={() => void recover('retry_current_node')}><RotateCcw size={14} />重试当前节点</NextButton><NextButton disabled={Boolean(busy) || !checkpoints.length} onClick={() => void recover('resume_checkpoint')}>从检查点继续</NextButton><NextButton disabled={Boolean(busy)} onClick={() => void recover('restart_run')}>使用原始输入重开</NextButton></div></section></div></NextPanel>
        <div className="nx-diagnostic-lower"><DiagnosticListPanel kind="events" title="事件时间线" items={events} loading={detailLoading} onExpand={() => setExpanded('events')} /><DiagnosticListPanel kind="checkpoints" title="检查点" items={checkpoints} loading={detailLoading} onExpand={() => setExpanded('checkpoints')} /></div>
        <NextPanel className="nx-artifact-panel" title="产物与交付" kicker="DELIVERY" action={<><b>{artifacts.length}</b><NextButton onClick={() => setExpanded('artifacts')}><Maximize2 size={14} />展开</NextButton></>}><div className="nx-artifact-row">{artifacts.length ? artifacts.slice(0, 4).map((artifact: any, index) => <article key={`${artifact.artifact_id || artifact.name}-${index}`}><strong>{artifact.name || '未命名产物'}</strong><span>{artifact.mime_type || artifact.type || 'file'}</span></article>) : <NextEmpty title="这个运行还没有可预览的产物" />}</div></NextPanel></>}</section>
    </div></div>
    <NextDialog title={expanded === 'events' ? '事件时间线' : expanded === 'checkpoints' ? '检查点' : '产物与交付'} eyebrow="RUN EVIDENCE" open={Boolean(expanded)} onClose={() => setExpanded('')} wide>{expanded === 'events' && <ExpandedEvents events={events} />}{expanded === 'checkpoints' && <ExpandedCheckpoints checkpoints={checkpoints} />}{expanded === 'artifacts' && <ExpandedArtifacts artifacts={artifacts} />}</NextDialog>
  </NextPage>
}

function DiagnosticListPanel({ kind, title, items, loading, onExpand }: { kind: 'events' | 'checkpoints'; title: string; items: any[]; loading: boolean; onExpand: () => void }) {
  return <NextPanel className="nx-evidence-list-panel" title={title} kicker={kind === 'events' ? 'EVENT TIMELINE' : 'CHECKPOINTS'} action={<><b>{items.length}</b><NextButton onClick={onExpand}><Maximize2 size={14} />展开</NextButton></>}><div className="nx-evidence-rows">{loading ? <NextLoading /> : items.length ? items.slice(kind === 'events' ? -8 : -8).reverse().map((item: any, index) => <div key={item.event_id || item.checkpoint_id || index}><NextStatus tone={kind === 'events' && String(item.type).includes('failed') ? 'danger' : item.outcome === 'completed' ? 'success' : 'neutral'}>{kind === 'events' ? item.state || item.type || '事件' : item.outcome || item.phase}</NextStatus><span><strong>{kind === 'events' ? eventText(item) : item.node_id || '未知节点'}</strong><small>{kind === 'events' ? item.type || 'system' : `${item.phase || '—'} · ${item.checkpoint_id || ''}`}</small></span><time>{formatNextDate(item.created_at || item.timestamp)}</time></div>) : <NextEmpty title={kind === 'events' ? '没有事件记录' : '没有检查点'} />}</div></NextPanel>
}
function ExpandedEvents({ events }: { events: FlowEvent[] }) { return <div className="nx-expanded-table">{events.map((event, index) => <div key={`${event.created_at}-${index}`}><time>{formatNextDate(event.created_at || event.timestamp)}</time><NextStatus tone={String(event.type).includes('failed') ? 'danger' : String(event.type).includes('completed') ? 'success' : 'neutral'}>{event.state || 'system'}</NextStatus><strong>{eventText(event)}</strong><code>{event.type || 'event'}</code></div>)}</div> }
function ExpandedCheckpoints({ checkpoints }: { checkpoints: any[] }) { return <div className="nx-expanded-table">{checkpoints.map((item) => <div key={item.checkpoint_id}><time>{formatNextDate(item.created_at)}</time><NextStatus tone={item.outcome === 'completed' ? 'success' : 'warning'}>{item.outcome || '未知'}</NextStatus><strong>{item.node_id || '未知节点'}</strong><code>{item.checkpoint_id}</code></div>)}</div> }
function ExpandedArtifacts({ artifacts }: { artifacts: any[] }) { return <div className="nx-expanded-artifacts">{artifacts.map((artifact, index) => <article key={`${artifact.artifact_id || artifact.name}-${index}`}><div><strong>{artifact.name}</strong><span>{artifact.mime_type || artifact.type}</span></div>{String(artifact.mime_type || '').startsWith('image/') && artifact.url ? <img src={artifact.url} alt={artifact.name} /> : artifact.url ? <a href={artifact.url} target="_blank" rel="noreferrer">打开产物</a> : <code>{artifact.display_path || artifact.path || '无可用路径'}</code>}</article>)}</div> }
