from __future__ import annotations

import argparse
import sys
import unittest
from pathlib import Path


# Keep the executable-maintenance tree free of generated bytecode artifacts.
sys.dont_write_bytecode = True


ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "src"
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(SOURCE_ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

from core.conformance import RecordingTestResult, build_conformance_report, write_conformance_report
from core.data_paths import CONFORMANCE_REPORT
from audit_protocol_governance import audit as audit_protocol_governance


TEST_GROUPS = ("conformance", "runtime", "studio", "llm", "api", "integration", "lab", "orchestration", "hygiene", "history", "browser")
ROOT_TEST_GROUP = "."


def discover_tests(pattern: str) -> unittest.TestSuite:
    suite = unittest.TestSuite()
    test_root = ROOT / "scripts" / "tests"
    suite.addTests(unittest.TestLoader().discover(str(test_root), pattern=pattern))
    for group in TEST_GROUPS:
        loader = unittest.TestLoader()
        suite.addTests(loader.discover(str(test_root / group), pattern=pattern))
    return suite


def undiscovered_test_groups(pattern: str) -> list[str]:
    test_root = ROOT / "scripts" / "tests"
    known = set(TEST_GROUPS) | {ROOT_TEST_GROUP}
    discovered = set()
    for path in test_root.rglob(pattern):
        relative = path.relative_to(test_root)
        discovered.add(relative.parts[0] if len(relative.parts) > 1 else ROOT_TEST_GROUP)
    return sorted(discovered - known)


def main() -> int:
    parser = argparse.ArgumentParser(description="Run conformance tests and emit a machine-readable report.")
    parser.add_argument("--pattern", default="test_*.py")
    parser.add_argument("--output", default=CONFORMANCE_REPORT.as_posix())
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()

    undiscovered = undiscovered_test_groups(args.pattern)
    if undiscovered:
        print("Conformance test discovery has unregistered test groups:")
        print("\n".join(f"- {group}" for group in undiscovered))
        return 1

    governance_errors = audit_protocol_governance(ROOT)
    if governance_errors:
        print("Protocol governance audit failed:")
        print("\n".join(f"- {error}" for error in governance_errors))
        return 1

    suite = discover_tests(args.pattern)
    runner = unittest.TextTestRunner(
        verbosity=1 if args.quiet else 2,
        resultclass=RecordingTestResult,
    )
    result = runner.run(suite)
    report = build_conformance_report(
        ROOT,
        result.case_results,
        started_at=getattr(result, "run_started_at", None),
    )
    target = write_conformance_report(ROOT, report, args.output)
    counts = report["capabilities"]["counts"]
    print(
        f"Conformance report: {target}\n"
        f"Tests: {report['tests']['status']} ({report['tests']['total']})\n"
        f"Capabilities: verified={counts['verified']} partial={counts['partial']} "
        f"unverified={counts['unverified']} failing={counts['failing']}"
    )
    return 0 if result.wasSuccessful() else 1


if __name__ == "__main__":
    raise SystemExit(main())
