import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Activity, Boxes, Braces, CheckCircle2, CircleAlert, FileSearch, GitCompareArrows, Network, Play, RefreshCw, Rocket, Send, ShieldCheck, SlidersHorizontal } from 'lucide-react'
import { developerApi } from './api'
import { json, pathDiff, semanticProjection, type AnyRecord } from './model'
import './styles.css'

type Data = Record<string, AnyRecord | null>
const value = (item: unknown) => typeof item === 'string' ? item : json(item)
const array = (value: unknown) => Array.isArray(value) ? value as AnyRecord[] : []
const status = (good: unknown) => good === true || good === 'ok' || good === 'ready' || good === 'passed'

function Panel({ title, icon, children, className = '' }: { title: string; icon: React.ReactNode; children: React.ReactNode; className?: string }) { return <section className={`panel ${className}`}><h2>{icon}{title}</h2>{children}</section> }
function ProjectJourneyCanvas({ graph }: { graph: AnyRecord }) {
  const nodes = array(graph.nodes); const edges = array(graph.edges)
  const levels = new Map<number, AnyRecord[]>(); nodes.forEach((node) => { const level = Number(node.level || 0); levels.set(level, [...(levels.get(level) || []), node]) })
  const positions = new Map<string, { x: number; y: number }>(); levels.forEach((items, level) => items.forEach((node, index) => positions.set(String(node.id), { x: 24 + level * 210, y: 40 + index * 88 })))
  const width = Math.max(460, (Math.max(...nodes.map((node) => Number(node.level || 0)), 0) + 1) * 210 + 24); const height = Math.max(170, ...[...levels.values()].map((items) => items.length * 88 + 36))
  const label = (item: unknown) => { const text = String(item || ''); return text.length > 22 ? `${text.slice(0, 21)}...` : text }
  return <section><h2>项目链路图</h2><svg aria-label="Project journey graph" viewBox={`0 0 ${width} ${height}`} width={width} height={height} role="img">{edges.map((edge) => { const from = positions.get(String(edge.from)); const to = positions.get(String(edge.to)); return from && to ? <line key={String(edge.id)} x1={from.x + 160} y1={from.y + 28} x2={to.x} y2={to.y + 28} stroke="currentColor"><title>{String(edge.relation || '')}</title></line> : null })}{nodes.map((node) => { const point = positions.get(String(node.id))!; return <g key={String(node.id)} transform={`translate(${point.x} ${point.y})`}><title>{String(node.label)}，{String(node.status)}</title><rect width="160" height="56" fill="none" stroke="currentColor" /><text x="8" y="22">{label(node.label)}</text><text x="8" y="44">{String(node.kind)} · {String(node.status)}</text></g> })}</svg></section>
}
function ProjectWorkspace({ projectId }: { projectId: string }) {
  const [project, setProject] = useState<AnyRecord | null>(null); const [error, setError] = useState('')
  useEffect(() => { developerApi.project(projectId).then((result) => setProject(result.developer as AnyRecord)).catch((reason) => setError(reason instanceof Error ? reason.message : 'Unable to load this project.')) }, [projectId])
  if (error) return <main><header><div><b>CARTRIDGEFLOW</b><span>Developer Console</span></div></header><p role="alert">{error}</p></main>
  if (!project) return <main><header><div><b>CARTRIDGEFLOW</b><span>Developer Console</span></div></header><p>Loading project...</p></main>
  const recipe = project.recipe as AnyRecord; const readiness = project.generation_readiness as AnyRecord; const steps = array(recipe?.steps); const journey = project.journey_graph as AnyRecord
  return <main><header><div><b>CARTRIDGEFLOW</b><span>Developer Console</span><small>project engineering workspace</small></div></header><section><h1>工程验证</h1><p>项目：{String(project.project_id)}</p><p>配方修订：{String(recipe?.revision ?? 'pending')}</p><p>工程状态：{readiness?.ready ? '可进入工程物化' : '等待创作配方完成'}</p><ProjectJourneyCanvas graph={journey} /><h2>已确认的配方步骤</h2><ul>{steps.map((step) => <li key={String(step.id)}>{String(step.intent)}</li>)}</ul><a href={String(project.creator_url)}>返回创作配方</a></section></main>
}

function Console() {
  const [flows, setFlows] = useState<AnyRecord[]>([]); const [id, setId] = useState(''); const [data, setData] = useState<Data>({}); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [view, setView] = useState<'semantic' | 'source'>('semantic'); const [selectedNode, setSelectedNode] = useState(''); const [patchText, setPatchText] = useState('{}'); const [message, setMessage] = useState(''); const [publishing, setPublishing] = useState(false)
  const load = async (flowId = id) => { if (!flowId) return; setLoading(true); setError(''); try {
    const detail = await developerApi.flow(flowId); const editable = Boolean((detail.cartridge as AnyRecord)?.editable); const protocol = ((detail.cartridge as AnyRecord)?.root_flow as AnyRecord | undefined)?.protocol as AnyRecord | undefined; const tuningSupported = String(protocol?.id || '') === 'CF-FARP' && Number(String(protocol?.version || '0')) >= 1.1
    const files = editable ? await developerApi.files(flowId) : { files: {} }
    const results = await Promise.allSettled([developerApi.resources(flowId), editable && tuningSupported ? developerApi.tuning(flowId) : Promise.resolve(null), developerApi.preflight(flowId), developerApi.conformance()])
    const valueAt = (index: number) => results[index].status === 'fulfilled' ? results[index].value : null
    const tuningFailure = results[1].status === 'rejected' ? (results[1].reason instanceof Error ? results[1].reason.message : 'Tuning projection is unavailable.') : ''
    const [resources, tuning, preflight, conformance] = [valueAt(0), valueAt(1), valueAt(2), valueAt(3)]
    const analysis = editable ? await developerApi.analyze(flowId, (files.files as AnyRecord) ?? {}) : null
    const validation = editable ? await developerApi.validate(flowId, (files.files as AnyRecord) ?? {}) : null
    setData({ detail, files, resources, tuning, preflight, conformance, analysis, validation, ...(!tuningSupported ? { tuning_failure: { message: `This flow declares ${String(protocol?.id || 'no protocol')}@${String(protocol?.version || 'unknown')}; tuning requires a trusted CF-FARP@1.1 or newer host.` } } : tuningFailure ? { tuning_failure: { message: tuningFailure } } : {}) })
  } catch (e) { setError(e instanceof Error ? e.message : 'Unable to reach the declared API') } finally { setLoading(false) } }
  useEffect(() => { developerApi.flows().then(({ items }) => { setFlows(items); const next = new URLSearchParams(location.search).get('flowId') || String(items[0]?.id || ''); setId(next); if (next) load(next) }).catch((e) => setError(e.message)) }, [])
  const semantic = useMemo(() => semanticProjection(data.detail ?? {}, data.analysis, data.resources), [data])
  const graph = (semantic.topology as AnyRecord | undefined) ?? {}; const nodes = array(graph.nodes); const edges = array(graph.edges)
  const revisions = array((data.tuning?.repository as AnyRecord | undefined)?.revisions); const raw = data.files?.files ?? {}; const materialized = (data.tuning?.tuning_context as AnyRecord | undefined) ?? {}; const diff = pathDiff(raw, materialized)
  const submitRevision = async () => { if (!id || !selectedNode) { setError('Select a declared flow node before creating a tuning revision.'); return } let patch: AnyRecord; try { patch = JSON.parse(patchText) as AnyRecord } catch { setError('Revision patch must be valid JSON.'); return }; setPublishing(true); setError(''); try { await developerApi.createRevision(id, selectedNode, { patch, author: 'developer-console', message: message || 'Console tuning revision' }); setNotice('Tuning revision created from the declared patch.'); await load(id) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create tuning revision.') } finally { setPublishing(false) } }
  const publish = async () => { if (!id) return; setPublishing(true); setError(''); try { const result = await developerApi.publishRelease(id, { author: 'developer-console', message: message || 'Console recipe release' }); const release = result.release as AnyRecord; setNotice(`Published ${String(release?.id || 'recipe release')}. Activate it explicitly after review.`); await load(id) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to publish recipe release.') } finally { setPublishing(false) } }
  const activate = async (releaseId: string) => { if (!id) return; setPublishing(true); setError(''); try { await developerApi.activateRelease(id, releaseId); setNotice(`Activated ${releaseId}.`); await load(id) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to activate recipe release.') } finally { setPublishing(false) } }
  return <main>
    <header><div><b>CARTRIDGEFLOW</b><span>Developer Console</span><small>declaration API only / development diagnostics</small></div><div className="header-actions"><select aria-label="Flow" value={id} onChange={(e) => { setId(e.target.value); load(e.target.value) }}>{flows.map((flow) => <option key={String(flow.id)} value={String(flow.id)}>{String(flow.name || flow.id)}</option>)}</select><button title="Refresh all declared projections" onClick={() => load()} disabled={loading}><RefreshCw size={16} />{loading ? 'Loading' : 'Refresh'}</button></div></header>
    {error && <div className="error"><CircleAlert size={16}/>{error}</div>}{notice && <div className="notice"><CheckCircle2 size={16}/>{notice}</div>}
    <nav><button className={view === 'semantic' ? 'active' : ''} onClick={() => setView('semantic')}><Network size={15}/>Semantic projection</button><button className={view === 'source' ? 'active' : ''} onClick={() => setView('source')}><Braces size={15}/>Raw declarations</button><span>Secrets are redacted at the client boundary.</span></nav>
    <div className="summary"><span><b>{Number(graph.node_count ?? nodes.length)}</b> nodes</span><span><b>{Number(graph.edge_count ?? edges.length)}</b> edges</span><span><b>{array((data.resources?.tools)).length}</b> tools</span><span className={status((data.validation as AnyRecord)?.valid) ? 'good' : 'warn'}>{status((data.validation as AnyRecord)?.valid) ? <CheckCircle2 size={15}/> : <CircleAlert size={15}/>} validation {String((data.validation as AnyRecord)?.valid ?? 'pending')}</span></div>
    {view === 'source' ? <Panel title="Raw declaration bundle" icon={<Braces size={17}/>} className="source"><pre>{json(raw)}</pre></Panel> : <div className="grid">
      <Panel title="Root Flow topology" icon={<Network size={17}/>} className="topology"><div className="flowmap">{nodes.map((node, index) => <div className="node" key={String(node.id)}><em>{index + 1}</em><strong>{String(node.title || node.label || node.id)}</strong><small>{String(node.type || node.kind || 'state')}</small></div>)}</div><div className="edges">{edges.map((edge, index) => <code key={index}>{String(edge.from || edge.source)} <span>--{String(edge.kind || edge.scope || 'sequence')}--&gt;</span> {String(edge.to || edge.target)}</code>)}</div></Panel>
      <Panel title="Protocol identity & typed contracts" icon={<ShieldCheck size={17}/>}><dl><dt>Protocol</dt><dd>{value((semantic.identity as AnyRecord)?.protocol)}</dd><dt>Flow</dt><dd>{String((semantic.identity as AnyRecord)?.id || 'unresolved')}</dd><dt>Contracts</dt><dd>{value(semantic.contracts)}</dd></dl></Panel>
      <Panel title="Prompts, recipes & materialization" icon={<SlidersHorizontal size={17}/>}><dl><dt>Recipe revision</dt><dd>{String((data.tuning?.repository as AnyRecord)?.repository_revision ?? 'not declared')}</dd><dt>Active release</dt><dd>{String((data.tuning?.repository as AnyRecord)?.active_release_id ?? 'draft')}</dd><dt>Materialization digest</dt><dd className="mono">{String(materialized.materialization_digest ?? 'pending')}</dd></dl>{data.tuning_failure && <p className="muted">Tuning projection unavailable: {String((data.tuning_failure as AnyRecord).message)}</p>}<div className="revision-list">{revisions.slice(-4).reverse().map((revision) => <div key={String(revision.id)}><b>{String(revision.node_id)}</b><span>{String(revision.message || revision.id)}</span><code>{value(revision.patch)}</code></div>)}</div><div className="tuning-actions"><select aria-label="Node for tuning" value={selectedNode} onChange={(event) => setSelectedNode(event.target.value)}><option value="">Select declared node</option>{nodes.map((node) => <option key={String(node.id)} value={String(node.id)}>{String(node.title || node.label || node.id)}</option>)}</select><textarea aria-label="Tuning patch JSON" value={patchText} onChange={(event) => setPatchText(event.target.value)} spellCheck={false} /><input aria-label="Revision message" value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Review note" /><div><button onClick={submitRevision} disabled={publishing || !selectedNode}><Send size={15}/>Create revision</button><button onClick={publish} disabled={publishing || Boolean(data.tuning_failure)}><Rocket size={15}/>Publish release</button></div></div></Panel>
      <Panel title="Model, tool & source bindings" icon={<Boxes size={17}/>}><pre>{json(semantic.bindings)}</pre><div className="tool-list">{array(data.resources?.tools).map((tool) => <span key={String(tool.id || tool.name)}>{String(tool.name || tool.id)} <i>{String(tool.status || tool.type || 'declared')}</i></span>)}</div></Panel>
      <Panel title="Precise declaration diff" icon={<GitCompareArrows size={17}/>}><p className="muted">Raw declarations versus the declared tuning materialization.</p>{diff.length ? <div className="diff">{diff.slice(0, 12).map((change) => <div key={change.path}><code>{change.path}</code><del>{value(change.before)}</del><ins>{value(change.after)}</ins></div>)}</div> : <p className="muted">No materialized delta is declared.</p>}<div className="release-list">{array((data.tuning?.repository as AnyRecord)?.releases).slice().reverse().map((release) => <div key={String(release.id)}><span>{String(release.id)}</span><button onClick={() => activate(String(release.id))} disabled={publishing || String((data.tuning?.repository as AnyRecord)?.active_release_id) === String(release.id)}><Play size={14}/>{String((data.tuning?.repository as AnyRecord)?.active_release_id) === String(release.id) ? 'Active' : 'Activate'}</button></div>)}</div></Panel>
      <Panel title="Validation, package preflight & probes" icon={<FileSearch size={17}/>}><div className="checks">{['compatibility', 'certification', 'environment', 'dependencies', 'models', 'resources', 'package_hygiene', 'portability'].map((key) => { const item = data.preflight?.[key] as AnyRecord | undefined; const state = item?.status ?? item?.ok; return <div key={key} className={status(state) ? 'ok' : 'attention'}>{status(state) ? <CheckCircle2 size={15}/> : <CircleAlert size={15}/>}<span>{key.replace('_', ' ')}</span><b>{String(state ?? 'unavailable')}</b></div> })}</div><h3><Activity size={15}/>Development probes</h3><pre>{json({ validation: data.validation, analysis_findings: data.analysis?.findings, conformance: data.conformance?.report })}</pre></Panel>
    </div>}
  </main>
}
function App() {
  const match = window.location.pathname.match(/^\/projects\/([^/]+)\/developer$/)
  return match?.[1] ? <ProjectWorkspace projectId={decodeURIComponent(match[1])} /> : <Console />
}
createRoot(document.getElementById('root')!).render(<App />)
