export const copy = {
  brand: '创作空间',
  unnamedProject: '未命名项目',
  disconnected: '未连接',
  connected: '已连接',
  themeLight: '浅色',
  themeDark: '深色',
  toggleTheme: '切换外观',
  emptyTitle: '画布是空的，这是正常的',
  emptyBeforeConnect: '先完成 AI 连接，画布就会开始响应你的输入',
  emptyBeforeDescribe: '描述你的目标，AI 会在这里把想法编排成可审核的方案',
  composePlaceholder: '例如：生成一份用户调研报告大纲',
  composeSubmit: '发给共创 AI',
  steward: '对话管家',
  stewardHint: '共创 AI 只帮你改方案，不进入运行时。',
  stewardWelcome: '点画布上的步骤告诉管家改哪里。按住 Shift 可以多选。',
  stewardPlaceholder: '继续补充、改方向，或先点卡片再说这一步',
  stewardClear: '取消选中',
  previewOnCanvas: '虚线卡片是预览，还没有替换原方案',
  impactAdded: '预览新增',
  impactRemoved: '将拿掉',
  stewardSend: '发给管家',
  stewardWhole: '整份方案',
  stewardStep: '当前步骤',
  stewardNoStep: '先在画布上点一个步骤',
  stewardPreview: '这是一版新大纲，还没有替换画布',
  stewardApply: '用这版',
  stewardReject: '先不用',
  stewardAdded: '会新增',
  stewardRemoved: '会拿掉',
  stewardKept: '会保留',
  stewardTalking: '正在听你这一轮补充',
  toggleSteward: '对话管家',
  composeHint: '按 Enter 发送',
  clarifyKicker: '关键澄清',
  clarifyPlaceholder: '用自己的话回答，或改描述',
  clarifySubmit: '继续',
  skipDirections: '先不选，改描述',
  chooseDirection: '用这个方向生成大纲',
  outcome: '会得到',
  whyItFits: '为何适合',
  goal: '目标',
  goalKept: '目标还在',
  generatingKicker: '正在生成',
  generatingTitle: '正在把目标编排成可审核步骤',
  generatingBody: '选定方向后的大纲会出现在画布上，生成期间可以停在这一页。',
  failKicker: '这次没有完成',
  failTitle: '没能给出可比较的方向',
  retry: '重试',
  timeout: 'AI 响应超时，请稍后重试。',
  discoverFail: '暂时无法生成新方向，请稍后重试。',
  composeFail: '这次整体编排没有完成，请重试。',
  packageBlocked: '还有步骤没有完成审核，暂时不能打包。',
  packageFail: '打包校验没有通过。',
  runnerFail: 'Desktop Runner 没有接收当前试运行包。',
  connectTitle: '连接共创 AI',
  connectHint: '测试通过后才会保存配置',
  provider: '服务商',
  baseUrl: '服务地址',
  apiKey: 'API Key',
  model: '模型',
  keyPlaceholder: 'sk-...',
  connectFooter: '未通过测试不会标记为已连接',
  cancel: '取消',
  testing: '正在测试',
  testConnect: '测试并连接',
  connectFail: '连接没有通过测试，请检查后重试。',
  close: '关闭',
  settings: '本机资源',
  settingsTitle: '本机资源池',
  settingsHint: '接口和工具属于这台机器。语义方案只声明角色和能力需求，Key 不会写进卡带。',
  settingsApis: '接口',
  settingsTools: '工具',
  settingsEmptyApis: '还没有运行时接口。共创 AI 只负责编排，真正执行时由宿主按角色绑定这里的连接。',
  settingsEmptyTools: '还没有本机工具。语义画布不会出现工具节点，打包后宿主按能力需求来匹配。',
  addApi: '添加接口',
  addTool: '添加工具',
  saveTool: '保存工具',
  deleteItem: '移除',
  enableItem: '启用',
  disableItem: '停用',
  testItem: '测试',
  activateAuthoring: '用作共创 AI',
  authoringBadge: '共创 AI',
  builtinBadge: '内置',
  poolFoot: '连接 ID 是本机插座编号。方案和节点只保存角色与能力需求，不保存 API Key 或 MCP 地址。',
  toolName: '名称',
  toolKind: '类型',
  toolEndpoint: '地址或命令',
  toolServer: '服务',
  toolAction: '动作',
  relationInforms: '主流程',
  relationProduces: '产出',
  relationUses: '需要能力',
  kindControl: '主流程',
  kindData: '数据',
  kindUses: '能力',
  relationFilter: '显示关系',
  nodeGoal: '节点目标',
  currentApproach: '当前做法',
  gapHint: '待补齐是方案的一部分，不是报错',
  goWorkshop: '打开第二层补齐',
  openLayer2: '打开第二层',
  layer2Kicker: '第二层 · 能力做法',
  layer2Hint: '原方案还在后面，这里只改这一步的内部做法',
  layer2Close: '回到方案',
  inspectLayer2: '查看内部做法',
  contractTitle: '这一步的交接',
  contractNeed: '能力需求',
  contractInputs: '从这些步骤获得',
  contractOutputs: '这一步产出给',
  contractUses: '依赖的能力',
  contractEmptyIn: '这一步不依赖上游数据',
  contractEmptyOut: '这一步不向下游产出',
  packBind: '打包后的宿主绑定',
  packBindBody: '宿主会按这个能力需求去匹配本机资源池。符合就可以沿用，不必把 Key 或执行器写进方案。',
  packUnbound: '尚未绑定实现',
  packBound: '已有可信做法',
  returnedFromWorkshop: '新做法已经回填到原方案，请继续审核这一步。',
  workshopOnCanvas: '去工坊',
  fields: '业务参数',
  saveFields: '保存参数修改',
  aiSuggestion: 'AI 建议',
  current: '当前',
  suggested: '建议',
  previewImpact: '预览影响',
  rejectSuggestion: '放弃建议',
  applySuggestion: '应用建议',
  refinePlaceholder: '用一句话说明希望怎么改这一步',
  generateSuggestion: '生成调整建议',
  deferConfirm: '暂不确认',
  confirmNext: '确认并下一步',
  confirmNode: '确认节点',
  confirmed: '已确认',
  review: '待审核',
  unresolved: '待补齐',
  downloadPackage: '下载试运行包',
  loadingProject: '正在读取项目',
  trialRun: '试运行今日日报',
  processing: '正在处理',
  trustWorkspace: '当前工作区可信',
  trustOrg: '组织可信',
  trustSystem: '系统可信',
  package: {
    fail: '打包没有通过',
    trust: '请在 Runner 确认发布者',
    installed: '已安装到本机 Runner',
    signed: '试运行包已签名',
    packing: '正在打包',
    notReady: '还不能打包',
    trustBody: '签名有效。请到 Desktop Runner 核对密钥指纹，不要在创作空间里绕过确认。',
    installedBody: '卡带已通过独立验签并安装，可以在 Runner 里放入真实样例。',
    signedBody: '可以把包发给 Desktop Runner，或先下载签名包。',
    notReadyBody: '全部必需步骤确认且无缺口后，才能生成签名试运行包。',
  },
  guidance: {
    connectTitle: '先连接共创 AI',
    connectDetail: '测试通过才能开始描述目标，Key 仅保存在本机',
    connectAction: '连接 AI',
    clarifyTitle: '回答这个关键问题',
    clarifyAction: '继续回答',
    chooseTitle: '在方向里选一个',
    chooseDetail: '未选定不会生成大纲',
    chooseAction: '查看方向',
    describeTitle: '用一句话描述你想得到的结果',
    describeDetail: 'AI 会把目标拆解成可审核的语义方案，出现在画布上',
    completeGap: (label: string) => `补齐「${label}」`,
    reviewNode: (label: string) => `审核「${label}」`,
    startGap: '开始补齐',
    prepareTitle: '方案已完成审核',
    prepareAction: '准备试运行',
    trustTitle: '请确认本地发布者',
    trustDetail: '请到 Desktop Runner 核对密钥指纹',
    trustAction: '前往确认',
    installedTitle: '已送入 Desktop Runner',
    installedDetail: '可以在 Runner 里用真实样例试运行',
    openRunner: '打开 Runner',
    runnerReadyTitle: 'Desktop Runner 已就绪',
    runnerReadyDetail: '把当前签名包送入 Runner',
    deliverAction: '发送到 Runner',
    downloadTitle: '试运行包已就绪',
    downloadDetail: 'Runner 尚未连通，可以先下载签名包',
    downloadAction: '下载试运行包',
  },
} as const
